### ISSUE TITLE
create hello world example using Ampersandjs framework

### ISSUE THREAD

**Issue by hermwong** [hermwong/phonegap-app-desktop-electron-prototype#3]
use Ampersandjs to create the hello world example

**Comment by hermwong** [comment]
the example app now implements an `ampersand-model`, next steps are to create a view using `ampersand-view`.

**Comment by vwasteels** [comment]
Interesting ! I'm actually looking to export an ampersandjs app to cordova, but I can't find resource on how to make the router deal with the absolute PATH iOS is giving it. eg. :

`Users/vincentwasteels/Library/Developer/CoreSimulator/Devices/68A21451-4130-43E7-B49A-970534D6959B/data/Containers/Bundle/Application/F1F982AB-0C93-4E97-B9F4-BDFF1E684AC9/Hello World.app/www/index.html`

instead of `/`

for the home page, did you already have to manage this ?
